version: "3.8"

services:
  front:
    build: ./front
    container_name: angular
    ports: 
      - 4201:80
    networks:
      - geoinquietos-network
    depends_on:
      - geoserver
  back:
    build:
      context: ./back
      target: dev
      args:
        - PORT=${NEST_PORT}
    container_name: nest
    ports: 
        - 3001:${NEST_PORT}
    env_file: .env
    networks:
      - geoinquietos-network
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
    depends_on:
      db:
        condition: service_healthy
  db:
    image: kartoza/postgis:${POSTGIS_VERSION_TAG}
    container_name: postgres
    restart: on-failure
    env_file: .env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      ALLOW_IP_RANGE: ${ALLOW_IP_RANGE}
      # FORCE_SSL: TRUE
      # SSL_MODE: allow
    ports:
      - 5433:${DATABASE_PORT}
    volumes:
      - geo-db-data:/var/lib/postgresql
      - ./postgres-config/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    networks:
      - geoinquietos-network
    healthcheck:
      test: "PGPASSWORD=${DATABASE_PASSWORD} pg_isready -h 127.0.0.1 -U ${DATABASE_USER} -d ${DATABASE_NAME}"
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 1m
  geoserver:
    image: kartoza/geoserver:${GS_VERSION}
    container_name: geoserver
    volumes:
      - geoserver-data:/opt/geoserver/data_dir
    ports:
       - 8080:8080
    restart: on-failure
    networks:
      - geoinquietos-network
    env_file: .env
    environment:
      GEOSERVER_DATA_DIR: '/opt/geoserver/data_dir'
      GEOWEBCACHE_CACHE_DIR: '/opt/geoserver/data_dir/gwc'
      GEOSERVER_ADMIN_PASSWORD: 'geoserver'
      GEOSERVER_ADMIN_USER: 'admin'
      INITIAL_MEMORY: '2G'
      MAXIMUM_MEMORY: '4G'
      STABLE_EXTENSIONS: 'css-plugin,vectortiles-plugin'
      COMMUNITY_EXTENSIONS: 'cog-plugin'
      GEOSERVER_CONTEXT_ROOT: 'geoserver'
      SAMPLE_DATA: True
      DB_BACKEND: POSTGRES               
      HOST: db                          
      POSTGRES_PORT: 5433             
      POSTGRES_DB: ${DATABASE_NAME}                  
      POSTGRES_USER: ${DATABASE_USER}    
      POSTGRES_PASS: ${DATABASE_PASSWORD}  
      # SSL_MODE: allow                    
      POSTGRES_SCHEMA: public           
      DISK_QUOTA_SIZE: 5 
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent --write-out 'HTTP CODE : %{http_code}\n' --output /dev/null -u admin:'geoserver' http://localhost:8080/geoserver/rest/about/version.xml"
      interval: 1m30s
      timeout: 10s
      retries: 3
      
volumes:
  geoserver-data: {}
  geo-db-data:

networks:
  geoinquietos-network:
    driver: bridge