version: "3.8"

services:
  front:
    build: ./front
    container_name: angular
    ports: 
      - 4201:80
  back:
    #build: ./back
    build:
      context: ./back
      target: dev
      args:
        - PORT=${NEST_PORT}
    container_name: nest
    ports: 
        - 3001:${NEST_PORT}
    env_file: .env
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    env_file: .env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - 5433:${DATABASE_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data  
  geoserver:
    image: kartoza/geoserver:2.22.0
    container_name: geoserver
    volumes:
      - geoserver-data:/opt/geoserver/data_dir
    ports:
       - 8080:8080
    restart: on-failure
    env_file: .env
    environment:
      GEOSERVER_DATA_DIR: '/opt/geoserver/data_dir'
      GEOWEBCACHE_CACHE_DIR: '/opt/geoserver/data_dir/gwc'
      GEOSERVER_ADMIN_PASSWORD: 'geoserver'
      GEOSERVER_ADMIN_USER: 'admin'
      INITIAL_MEMORY: '2G'
      MAXIMUM_MEMORY: '4G'
      STABLE_EXTENSIONS: 'css-plugin,vectortiles-plugin'
      COMMUNITY_EXTENSIONS: 'cog-plugin'
      GEOSERVER_CONTEXT_ROOT: 'geoserver'
      SAMPLE_DATA: True
      DB_BACKEND: POSTGRES               
      HOST: db                          
      POSTGRES_PORT: 5433             
      POSTGRES_DB: ${DATABASE_NAME}                  
      POSTGRES_USER: ${DATABASE_USER}    
      POSTGRES_PASS: ${DATABASE_PASSWORD}  
      SSL_MODE: allow                    
      POSTGRES_SCHEMA: public           
      DISK_QUOTA_SIZE: 5 
    healthcheck:
      test: "curl --fail --silent --write-out 'HTTP CODE : %{http_code}\n' --output /dev/null -u admin:'geoserver' http://localhost:8080/geoserver/rest/about/version.xml"
      interval: 1m30s
      timeout: 10s
      retries: 3
      
volumes:
  geoserver-data: {}
  postgres_data: